### ISSUE TITLE
Example 7.6.1 (Third Tutorial): unintentional change from Pollen markup mode to Pollen preprocessor mode?

### ISSUE THREAD

**Issue by th** [mbutterick/pollen#107]
Hi,

you've changed article.html.pm to article.html.pp when fixing issue #106.

I think that was wrong, because now you're not getting the X-expression, just the output as a string.

Or if that was intentional, "The result:" should be followed by

Pi is close to 3.141592653589793.
The hyperbolic sine of pi is close to 11.548739357257748.

instead of

'(root "Pi is close to " "3.141592653589793" "." "\n" "The hyperbolic sine of pi is close to " "11.548739357257748" "." "\n")

**Comment by mbutterick** [comment]
Fixed.
