### ISSUE TITLE
Misaligned indentation on DrRacket

### ISSUE THREAD

**Issue by leafac** [mbutterick/pollen#113]
I was working through the [Quick tour](http://docs.racket-lang.org/pollen/quick-tour.html) and noticed the indentation generated by DrRacket in `uptown.html.pm` when hitting `Cmd+I` is the following:

```racket
#lang pollen

◊headline{Pollen markup}

◊items{
       ◊item{You ◊strong{wanted} it—you ◊em{got} it.}
        ◊item{◊link["https://google.com/search?q=racket"]{search for Racket}}
        }
```

Similarly, when writing and hitting Enter, the cursor is placed in those strange columns.

Is this expected? If not, how do I work around it?

I'm using Pollen checksum `72c9e781...` on Racket 6.5 on OS X.

Thanks a lot.

**Comment by mbutterick** [comment]
Looks like a bug. I will investigate further.

**Comment by leafac** [comment]
Thanks a lot for the quick answer and for investigating. How can I help? Does the issue happen to you too?

**Comment by mbutterick** [comment]
Your sample now indents correctly:

```racket
#lang pollen

◊headline{Pollen markup}

◊items{
 ◊item{You ◊strong{wanted} it—you ◊em{got} it.}
 ◊item{◊link["https://google.com/search?q=racket"]{search for Racket}}
}
```

**Comment by leafac** [comment]
I update the package and can confirm that DrRacket now indents as you showed above.

Thanks a lot for the fix 👍
