### ISSUE TITLE
Pollen installation failed

### ISSUE THREAD

**Issue by digifu** [mbutterick/pollen#121]
Hey, sorry if this isn't the right place, but I don't know where I should ask about this install problem instead.

I installed racket. I can start drracket. But when I try to install pollen, via terminal or drracket, I always get this fail message. I am working with ubuntu 14.04 and tried with and without sudo.

Do you have any idea what could cause this problem?

---------------------
ssl-connect: connect failed (error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error)
  context...:
   /usr/share/racket/collects/openssl/mzssl.rkt:1207:8: loop
   /usr/share/racket/collects/net/url.rkt:222:2: redirection-loop
   /usr/share/racket/collects/pkg/util.rkt:33:0: call/input-url+2005
   /usr/share/racket/collects/pkg/lib.rkt:226:3: for-loop
   /usr/share/racket/collects/pkg/lib.rkt:224:0: package-index-lookup
   /usr/share/racket/collects/pkg/lib.rkt:459:2: install-package228
   /usr/share/racket/collects/pkg/lib.rkt:449:0: install-packages55
   /usr/share/racket/collects/racket/file.rkt:295:8
   /usr/share/racket/collects/racket/file.rkt:284:0: call-with-file-lock24
   /usr/share/racket/collects/mrlib/terminal.rkt:150:7
   /usr/share/racket/collects/mred/private/wx/common/queue.rkt:451:6
   /usr/share/racket/collects/mred/private/wx/common/queue.rkt:502:32
   /usr/share/racket/collects/racket/private/more-scheme.rkt:146:2: call-with-break-parameterization
   /usr/share/racket/collects/mred/private/wx/common/queue.rkt:397:18: loop

--------------

**Comment by mbutterick** [comment]
It seems like a problem with the Racket package server. Can you install anything else listed on http://pkgs.racket-lang.org or is it only Pollen that fails?

**Comment by digifu** [comment]
I've tried several packages. It's always the same fail message.

**Comment by digifu** [comment]
Ok, I found the problem. I checked the version numbers and found that the installed version was 5.3. I don't know why it was the wrong version. I included the ppa and installed.
But anyway, I solved it with a simple 

`sudo apt-get install racket`

Now, the racket version is 6.5, and the installation of pollen worked fine.

Thanks for your quick help
