### ISSUE TITLE
How to specify a dest directory when using `raco pollen start`?

### ISSUE THREAD

**Issue by Airead** [mbutterick/pollen#122]
How to specify a dest directory when using `raco pollen start`?

It will make my source directory clean

**Comment by mbutterick** [comment]
That can't be done, sorry.

**Comment by mbutterick** [comment]
PS [Longer discussion of this topic](https://groups.google.com/d/topic/pollenpub/TCineGx-N8E/discussion). In short, dealing with filesystems is something I try to minimize, because it’s full of subtle traps for the unwary.
