### ISSUE TITLE
"raco pollen help" falsely advertises an output directory for rendering

### ISSUE THREAD

**Issue by agmck** [mbutterick/pollen#125]
raco pollen render ignores the destination directory argument.

eg. if i use the command "raco pollen render src/ dest/", the destination argument is ignored and all source files are rendered to the same directory in which they reside. This is consistent with what is described in pollen documentation, but contradicts "raco pollen help" which claims:

"render  [dir] [dest]   render project in dir (default is current dir) to dest (default is desktop)"

Suggested solution: update the raco pollen help comment to remove mention of [dest].

"raco pollen publish" can be used as an additional step to render pollen files into a destination directory.

**Comment by mbutterick** [comment]
False advertising indeed. Thanks.
