### ISSUE TITLE
E-Book Feature Request: "Link to this heading" on hover or click.

### ISSUE THREAD

**Issue by gmlewis** [mbutterick/pollen#129]
"Beautiful Racket" is looking fantastic. One thing I would really like to see, both in Pollen-generated e-books and in Scribble-generated documentation is the ability to bookmark a particular heading.

This would allow me to pause at a section break and I could more easily come back to that point on the same (or a different) device by visiting the saved bookmark.

I noticed that you already have the start of this feature (as does Scribble), but the generated "anchor" looks like it is more for machine use than for human use.

For an example of what I'm talking about, please visit: https://github.com/mbutterick/pollen
and then hover your mouse over the first section entitled "Pollen: the book is a program".
Note the adorable chain link icon that appears... now click on it and you get a URL that will bring you back to this exact section in your browser... it resolves in this case to: https://github.com/mbutterick/pollen#pollen-the-book-is-a-program-
This isn't a great example because the page is short, but when the page is more than one screenful, it is a really nice feature to have.

Thanks!

**Comment by mbutterick** [comment]
Thank you. I appreciate the suggestion. Could you clarify, however: what’s the difference between what you're suggesting, and what happens in Beautiful Racket when you click on a paragraph or heading (= a shortlink appears above a comment form)?

**Comment by gmlewis** [comment]
Hmmm... it looks like maybe I'm totally confused here.  Beautiful Racket doesn't seem to have this problem at all.  It looks like what I actually meant was the Pollen documentation... which I'm guessing was written in Scribble.  Ah, yes.  I apologize.  Feel free to close this request... it really should be filed to Scribble.

Here's an example... if I go to http://docs.racket-lang.org/pollen/Pagetree.html#%28part._.Making_pagetrees_by_hand%29
and click on the heading, I see this:
```
14.5.3 Nesting pagetrees

Link to this section with
 @secref["Nesting_pagetrees" #:doc '(lib "pollen/scribblings/pollen.scrbl")]
```
but if I had just scrolled down to that point, I wouldn't get the direct link... but instead have to scroll to the top, match the "Nesting pagetrees" and then click on that link to give me the URL.

Anyway... great job, keep up the great work... it is my goal to learn Pollen (and Racket because of Pollen).  Feel free to close... Heck, I'll close it.  :-)

**Comment by mbutterick** [comment]
OK, I see. Yes, the links revealed in the Scribble docs are for documentation writers who want to create a cross-reference. FWIW the direct / bookmarkable URLs for each section are listed in the left-hand nav bar, but I see what you mean about making them available next to the relevant section heading. (Since I designed the layout of the Scribble docs too, this will probably end up in my lap anyhow ;)

**Comment by gmlewis** [comment]
Sorry for hijacking an old thread, but I don't know how to contact you otherwise... (my email is my GitHub username followed by at google dot com in case you ever wish to contact me directly).
I thought you might be interested in this blog post: https://backchannel.com/how-the-web-became-unreadable-a781ddc711b6
