### ISSUE TITLE
Error in Tutorial 1

### ISSUE THREAD

**Issue by th** [mbutterick/pollen#133]
In 5.5.3 you're supposed to try
```

#lang pollen
 
◊(void) ; this will become an empty string
◊(string->path "foo")
◊#\C
◊sqrt
◊(sqrt 2)
◊(list 1 2 3 4 5)
◊(map sqrt (list 1 2 3 4 5))
```

But ◊sqrt leads to "Racket\6.7\pkgs\pollen\pollen\private\main-base.rkt:54:67: pollen: Can't convert procedure #<procedure:sqrt> to string"

**Comment by mbutterick** [comment]
Thanks! Fixed.
