### ISSUE TITLE
Error in smart-quote rendering

### ISSUE THREAD

**Issue by olivertaylor** [mbutterick/pollen#136]
Given this example:

`This is a "◊em{simple}" --- test.`

The result is:

`This is a "<em>simple</em>“—test.`

The output should be:

`This is a “<em>simple</em>”—test.`

**Comment by mbutterick** [comment]
The `smart-quotes` function is “shallow” in the sense that it only looks to the immediate left & right to determine what kind of curly quote to use (I concede this is not ideal, but that is why it’s relegated to the `unstable` collection.)

The problem with putting an embedded X-expression flush against to the quote is that you’d have to descend into the X-expression to find out if the next character triggers a curly quote. Your example is simple, but in fact the X-expression could be nested to any depth. This seems potentially messy & slow. Though it’s probably just a matter of trying harder.

**Comment by mbutterick** [comment]
```racket
#lang pollen/markup
◊(require pollen/unstable/typography)
◊(define (root . xs) (smart-quotes `(root ,@xs)))

This is a "◊em{simple}" --- test.
```

```
'(root "This is a “" (em "simple") "” --- test.")
```

**Comment by olivertaylor** [comment]
Thanks!
