### ISSUE TITLE
cannot reference an identifier before its definition

### ISSUE THREAD

**Issue by archaeron** [mbutterick/pollen#137]
hey

I wanted to try pollen on windows and did:

```sh
raco pkg install pollen
raco pollen start
```

and get:

```
link: bad variable linkage;
 reference to a variable that is uninitialized
  reference phase level: 0
  variable module: "C:\Users\arch\AppData\Roaming\Racket\6.7\pkgs\pollen\pollen\private\file-utils.rkt"
  variable phase: 0
  reference in module: "C:\Users\arch\AppData\Roaming\Racket\6.7\pkgs\pollen\pollen\private\cache-utils.rkt"
  in: idY160.0
```

I don't know a lot about Racket yet and not sure if it's supposed to work on windows, but let me know if I can help you.

**Comment by mbutterick** [comment]
It works the same on Windows / Linux / Mac OS. This error, however, is a generic Racket error that stems from outdated bytecode files. To update the Pollen bytecode, try:

`raco setup pollen`

And then try running Pollen again. If that doesn't work, try 

`raco setup`

which will update the bytecode files for everything.

**Comment by archaeron** [comment]
you where right. Something with my racket installation was broken. Sorry :)

thanks a lot!
