### ISSUE TITLE
Can't save file as .pp in DrRacket

### ISSUE THREAD

**Issue by alecramsay** [mbutterick/pollen#14]
[Matthew--I figured out what was going on. Thanks for your help. Here are the details for everyone's benefit.]

I'm using DrRacket on Mac OS X. When following the "Quick tour" here (http://mbutterick.github.io/pollen/doc/quick-tour.html) I had significant difficulty saving files with the .pp extension. It turns out that I was getting hung up by the UI in DrRacket dialog.

These are the more elaborated instructions for saving a file as .pp in DrRacket:
- Press Save 
- In Save dialog enter the file name that you (e.g., hello.txt.pp). There are two different ways to do this
- One way is to press the "Hide Extension" checkbox and enter the file name
- The other way is to manually remove the .rkt extension that is automatically appended to file names (e.g., hello.txt.pp.rkt). When you do this, the “Hide Extension” checkbox will automatically become checked.
- Either way press Save, and
- In the popup dialog, press “Use .pp”

Note: You can't get just the file name you want to show up AND the "Hide Extension" to NOT be checked!

**Comment by mbutterick** [comment]
I pushed a workaround (https://github.com/mbutterick/pollen/commit/7bfd403023e86e39a9c3a63f6ec5fa6e51b21506) for this issue. More info at issue https://github.com/mbutterick/pollen/issues/34.
