### ISSUE TITLE
Embed pictures with pict?

### ISSUE THREAD

**Issue by jonsterling** [mbutterick/pollen#140]
I have seen that it is possible in Scribble to embed pictures generated with `pict` just by writing code like this in a document:

```racket
(require pict)
@(colorize (filled-ellipse 40 40) "beige").
```

I tried to do the same in a pollen page as follows:

```racket
◊(colorize (filled-ellipse 40 40) "beige").
```

But I received a contract violation:
```
decode-elements: contract violation
  expected: txexpr-elements?
  ...
```

Is there a proper way to do what I wanted?

**Comment by mbutterick** [comment]
Scribble is converting the `pict` object to a `png`, saving it, and generating a link to the new file. So you could make a macro that does the same housekeeping:

`test.html.pm`
```racket
#lang pollen
◊(require pict)
◊(pict-as-png (colorize (filled-ellipse 40 40) "red"))
```

`pollen.rkt`
```racket
#lang racket/base
(require racket/class pict (for-syntax racket/base racket/syntax))
(provide pict-as-png)

(define-syntax (pict-as-png stx)
  (syntax-case stx ()
    [(_ EXPR)
     (with-syntax ([temp-name (generate-temporary)])
       #'(let ([png-name (format "~a.png" 'temp-name)])
           (send (pict->bitmap EXPR) save-file png-name 'png)
           `(img ((src ,png-name)))))]))
```

**Comment by jonsterling** [comment]
@mbutterick Thank you very much for the help! Another thing I have tried out (which worked) is encoding the image as base-64 and inlining it into the html. Your solution is probably better for caching purposes.

**Comment by mbutterick** [comment]
Sure. The main idea is that whatever comes back from your Pollen function has to be something that counts as a `txexpr-element?`

Though it seems to be immovable folk wisdom at this point, I would [not necessarily assume](http://practicaltypography.com/the-scorpion-express.html#the-file-size-myth) that the base64 approach is slower.
