### ISSUE TITLE
Description of typing lozenge using Unicode input method

### ISSUE THREAD

**Issue by rrthomas** [mbutterick/pollen#141]
First, you list this under "Ubuntu", but it ought to work in all sorts of places, as it's a standard (ISO 14755): see https://en.wikipedia.org/wiki/Unicode_input

Secondly, you omit that after typing the code you need to press Space or Enter to complete it and get the glyph to display.

On the whole, it might be good to direct people to Wikipedia, as it gives a lot more detailed info than you have room for!

**Comment by mbutterick** [comment]
I don’t use Ubuntu or other Linuxes in depth so I don’t know what would be accurate to say. I invite you to edit the docs with more detailed info — the source file is here:

https://github.com/mbutterick/pollen/blob/master/pollen/scribblings/command.scrbl#L20

**Comment by rrthomas** [comment]
Wilco, I'll send a pull request. My instinct is to be accurate but imprecise: while I appreciate that you're trying to overcome resistance to an unusual feature (the need to use a character not readily available on keyboards), you should still minimise the degree to which you're doing tech support for something that has nothing to do with Pollen itself.

**Comment by mbutterick** [comment]
Closed by #142.
