### ISSUE TITLE
Are Pollen's docs not open source?

### ISSUE THREAD

**Issue by clozach** [mbutterick/pollen#156]
I just spent 3 hours trying to figure out how to submit a pull request in order to fix a typo. Well, truth be told, I spent about 20 minutes trying to find the repo for the docs, and about 160 minutes reading a [discovery](https://craigmod.com/journal/post_artifact/#ref-29) along the way, along with a variety of wonderful old articles through first- and second order links nested therein. 😬

Anyway, I'm officially giving up on making this correction myself. This should be sufficient for you to fix the typo:

_Location_
http://docs.racket-lang.org/pollen/first-tutorial.html

_Original_
> To make a **Racket**-style command, just take any Racket command and put the lozenge character ◊ in front of it.

_Fixed_
> To make a **Pollen**-style command, just take any Racket command and put the lozenge character ◊ in front of it.

Cheers!

**Comment by mbutterick** [comment]
Thank you, but that’s not a typo. Those are, in fact, Racket-style commands.

**Comment by mbutterick** [comment]
FWIW the source for that documentation page is [part of this repo](https://github.com/mbutterick/pollen/blob/master/pollen/scribblings/tutorial-first.scrbl).
