### ISSUE TITLE
current-pagenode in metas

### ISSUE THREAD

**Issue by jlorieau** [mbutterick/pollen#167]
The 'here-path' string is included in the `metas` hash table. The 'here-path' is an absolute path. However, to use this path as a pagenode for querying against the current pagetree, the user must strip the path up to the current project directory, possibly change the extension and convert the string to a symbol.

In this issue, I am suggesting adding a 'here-pagenode' or 'current-pagenode' entry in the `metas` hash table with a pagenode (symbol) for the current target pagenode.

**Comment by mbutterick** [comment]
What’s the difference between [`path->pagenode`](https://docs.racket-lang.org/pollen/Pagetree.html?q=path-%3Epagenode#%28def._%28%28lib._pollen%2Fpagetree..rkt%29._path-~3epagenode%29%29) and what you describe?

**Comment by jlorieau** [comment]
Thanks for the note. I wasn't aware of this function, and it appears to workup the here-path nicely. A convenience entry in `metas` may still be useful to users, but the workup is fairly trivial with `page->pagenode`.
