### ISSUE TITLE
(simple) dependency tracking support

### ISSUE THREAD

**Issue by lobisquit** [mbutterick/pollen#168]
Hi!

I am currently writing my CV with Pollen and code in `pollen.rkt` file has got really messy.

So I decided to split it into some Racket files to require from the main `pollen.rkt` source. Everything renders properly, but modifications in dependencies are not tracked, as specified in the [documentation](http://docs.racket-lang.org/pollen/Cache.html?q=dependency#%28part._.Scope_of_dependency_tracking%29).

I agree with the design decision, but is there some way to tweak Pollen to track a **fixed list** of `rkt` files (other than the main one)?

**Comment by lobisquit** [comment]
Nevermind, found [this discussion](https://groups.google.com/forum/#!topic/pollenpub/tUHfr8RxVFs): basically changing another `rkt` in watch-list would just recompile everything anyway (inlcuded untouched `pollen.rkt`), so it is equivalent to keep no cache at all.

**Comment by mbutterick** [comment]
I’m persuaded that it could be more useful than deactivating the cache altogether. It has been added as the new setup value `compile-cache-watchlist`.

**Comment by mbutterick** [comment]
Actually let's call it `cache-watchlist` instead, since it affects both the render cache and compile cache.

**Comment by lobisquit** [comment]
Thanks for the support 👍
