### ISSUE TITLE
‘raco pollen render’ doesn’t work in Directory mode

### ISSUE THREAD

**Issue by leafac** [mbutterick/pollen#172]
Consider the project:

```racket
;; my-book/index.txt.pm
#lang pollen

Hi
```

```racket
;; my-book/index.ptree
#lang pollen

index.txt
```

Now try to render it:

```
$ raco pollen version
1.3.1679.1017
$ raco pollen render my-book/
rendering preproc & pagetree files in directory /Users/leafac/Downloads/my-book/
$ raco pollen render my-book/index.ptree
rendering my-book/index.ptree
$ cd my-book/ && raco pollen render
rendering preproc & pagetree files in directory /Users/leafac/Downloads/my-book/
rendering: /index.txt.pm as /index.txt
cpu time: 167 real time: 198 gc time: 35
```

`raco pollen render my-book/` ([**Directory mode**](http://docs.racket-lang.org/pollen/raco-pollen.html#%28part._raco_pollen_render%29)) doesn’t render `index.txt`, but `cd`ing into the directory and calling `raco pollen render` from there (**Source mode**) does.

This wasn’t the case a few weeks ago. Maybe it has something to do with the introduction of the `--subdir` flag?

**Comment by mbutterick** [comment]
You’re right — it should’ve been treating the first directory argument as the project root, and wasn’t.

**Comment by leafac** [comment]
Thank you 😀
