### ISSUE TITLE
Return non-zero exit code if raco pollen subcommand is unrecognized

### ISSUE THREAD

**Issue by hkrish** [mbutterick/pollen#177]
Hi,

Currently, an invalid sub-command such as `raco pollen publsih` seems to return an exit code `0` to the shell. Can you please change it so that it returns a non-zero value.

This is quite useful when wrapping pollen command in a shell script or other racket programs.

Thank you

**Comment by mbutterick** [comment]
Consistent with other `raco` commands, it will return `1` for an invalid argument.
