### ISSUE TITLE
Support a setup that reverted #%top to its usual meaning

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen#183]
Per https://groups.google.com/forum/#!searchin/pollenpub/unbound%7Csort:date/pollenpub/gpRk-s1cMNA/Kji1D73aDwAJ, it would be nice if there's an option to opt-out of Pollen's `#%top` overriding. This can be done by either providing a setup value or a new (sub)language. A setup value might be more preferable since Pollen has sublanguages like `#lang pollen/markup`, `#lang pollen/ptree`, etc. already, and it wouldn't interact well with this orthogonal feature.

**Comment by mbutterick** [comment]
I’ve pushed a patch for this. Why don’t you try it out and see if it does what you expect. If so, I’ll add it to the docs.

I’ve introduced a new `setup` value called `allow-unbound-ids`. If set to `#false`, it will raise an error for unbound identifiers (= the typical `#%top` behavior):

```racket
#lang racket/base
(provide (all-defined-out))

(module setup racket/base
  (provide allow-unbound-ids)
  (define allow-unbound-ids #false))
```

**Comment by sorawee** [comment]
Yup, this is exactly what I expect. Thank you again :)

**Comment by sorawee** [comment]
Re: root, right, that would be an unbound id error. It's a one time thing to do, and you need `pollen.rkt` to setup `allow-unbound-ids` already anyway, so it's relatively easy to do.

**Comment by mbutterick** [comment]
In Pollen 2.0, I changed the name of this setup to `allow-unbound-ids?` (with `?`) to be consistent with the usual convention for predicate-style functions. It had not yet been documented so the provisional `allow-unbound-ids` (without `?`) is no longer supported.
