### ISSUE TITLE
define-metas and select-from-metas have inconsistent signature

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen#184]
In a sense that I can:

```
(define-metas foo (1 2 3))
```

and there's no error, but then when I `(select-from-metas 'foo metas)`, I get a contract error that `'(1 2 3)` is not a `xexpr`.

I see no reason why we should limit metas to just `xexpr` (for example, it might be useful to have a metadata about raw date and time, which can be represented as a list of numbers), but if restricting to only `xexpr` is your decision, it probably should error out at `define-metas`, not `select-from-metas`.

**Comment by mbutterick** [comment]
I suppose you're right that a meta value needn't be restricted to an `xexpr`. However, `metas` are extracted before the file is run, and cached to disk, so the meta value still needs to be something that is a) not computed and b) serializable.
