### ISSUE TITLE
Consider using lazy-require

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen#190]
I tried:

```
(lazy-require
 ["../render.rkt" (render-batch)])
```

in `command.rkt` instead of simply `(require "../render.rkt")`. This simple change consistently speeds up `raco pollen reset` (and other commands that don't render) by 0.6s. I think there are a lot more low hanging fruit that we can find.

**Comment by mbutterick** [comment]
I didn’t even know about `lazy-require` so I imagine you’re right.
