### ISSUE TITLE
accessing source files results in errors and directory creation

### ISSUE THREAD

**Issue by sorawee** [mbutterick/pollen#191]
Say I access `http://localhost:8080/a/b/c/blah.pm` (which might or might not exist) in browser. This results in the following exception:

```
cached-metas: contract violation
  expected: path to existing file
  given: "/path/to/a/b/c/blah.pm"
```

In case that `a/b/c` doesn't exist, Pollen will create the directories.

This seems bizarre, and the side effect is even more bizarre. I expect that I will simply get the 404 page.

**Comment by mbutterick** [comment]
Agreed. Fixed.
