### ISSUE TITLE
HTML output not matching Quick Start example (rendering literally)

### ISSUE THREAD

**Issue by fncll** [mbutterick/pollen#206]
I installed Racket 7.3 and Pollen (2.0.2142.1197). When I use the code from the Quick Start to test HTML generation:

```
#lang pollen
<body style="margin: 5em; border:1px solid black">
5em is the inset.
</body>
```

The output doesn't match the description, but is instead wrapped in code that displays it literally:

```
<!DOCTYPE html><html><head><title>Pollen</title><meta charset="UTF-8"/><link rel="stylesheet" type="text/css" href="/poldash.css"/></head><body><tt>&lt;body style="margin: 5em; border:1px solid black"&gt;
5em is the inset.
&lt;/body&gt;</tt><div id="pollen-logo"></div></body></html>
```

What is going on?

**Comment by mbutterick** [comment]
What is the filename?

**Comment by mbutterick** [comment]
(In this case, the extension needs to be `.pp` not `.pm`, because the source contains raw HTML)

**Comment by fncll** [comment]
The filename is `margin.html.pp` -- I am viewing the file using the `out` link on the dashboard and what I shared above is when I use View Source.

**Comment by mbutterick** [comment]
Right, the `out` link shows you the literal output of the file, rendered as plain text. If you want to see the output of the file rendered in the browser as HTML, click on the link in the left column called `margin.html.pp`.

**Comment by fncll** [comment]
Sorry, I was being particularly dense!
