### ISSUE TITLE
Custom command-char leading to incorrect HTML output

### ISSUE THREAD

**Issue by cutculus** [mbutterick/pollen#210]
`raco pollen version` = 2.1.2229.709

I was trying out the tutorial

```
;; pollen.rkt
#lang racket/base

(require pollen/tag)
(provide (all-defined-out))
(define headline (default-tag-function 'h2))
(define items (default-tag-function 'ul))
(define item (default-tag-function 'li 'p))
(define (link url text) `(a ((href ,url)) ,text))

(module setup racket/base
  (provide (all-defined-out))
  (define command-char #\%)) ;; This is ok?

;; index.html.pm
#lang pollen

%headline{Pollen markup}

%items{
  %item{You %strong{wanted} it — you %em{got} it.}
  %item{%link["https://google.com/search?q=racket"]{search for Racket}}
}
```

However, when I run `raco pollen render index.html.pm`, the output `index.html` is simply

```
◊(->html (html (head (meta #:charset "UTF-8")) (body doc)))
```

Am I doing something incorrectly or is this a bug?

**Comment by mbutterick** [comment]
The default HTML template uses a lozenge as the command char. You would need to make your own template (even just copying the default) with your custom command char.

**Comment by cutculus** [comment]
Thanks, that explains it! In case anyone is reading this in the future: I followed the instructions [here](https://docs.racket-lang.org/pollen/second-tutorial.html#(part._tutorial-2._.The_doc_export_and_the_-_html_function)) and added a `template.html.p` file to fix the issue:

```
%(->html (html (head (meta #:charset "UTF-8")) (body doc)))
```
