### ISSUE TITLE
Subdirectories and `here`, `previous`, and `next`

### ISSUE THREAD

**Issue by sturgman** [mbutterick/pollen#211]
Hello!

I am currently going through the pollen documentation setting up my directories as follows:
```
C:\some\path\pollentest
C:\some\path\pollentest\tutorial1
C:\some\path\pollentest\tutorial2
.
.
.
```
I ran `raco pollen start` from the `pollentest` directory. The decision to set up like this led me to confusion when doing the pagetree section of tutorial2. In particular, this snippet:
```
<html>
--
<head>
<meta charset="UTF-8">
<title>◊(select 'h1 doc), by MB</title>
<link rel="stylesheet" type="text/css" href="styles.css" />
</head>
<body>◊(->html doc)
The current page is called ◊\|here\|.
The previous is ◊\|(previous here)\|.
The next is ◊\|(next here)\|.
</body>
</html>
```
I could not get the previous and next pages to render. With this template, the rendered text looked like this:

> The current page is barticle.html. The previous page is . The next page is .

It took me some time to realize that this was because of my directory structure. If I start pollen in the tutorial2 directory, everything works fine. I suspect this happens because `◊|here|` returns the full path name of the current page relative to the place where I started the pollen server, while `previous` and `select` expect just the file name of the current page. Is that correct?

I any case, I just wanted to provide some feedback on my experience. I figure later in the documentation I will find how to deal with subdirectories.

**Comment by mbutterick** [comment]
> The decision to set up like this led me to confusion … If I start pollen in the tutorial2 directory, everything works fine

The first tutorial asks readers to make a directory for the tutorial source files and then start the project server from this *same* directory. If what you’re saying is “when one follows the instructions, it works” then I agree 😉 (Or, if there’s an instruction that’s defective, I can fix it.)

**Comment by sturgman** [comment]
Fair enough!

Note that tutorial one also says: " For each directory in your project,
starting at the top, the project server displays a dashboard in your web
browser. The dashboard gives you an overview of the files in the directory,
and links to view them." which at the time gave me the impression that I
could do what I was doing...

I'll follow the instructions more closely from now on! 😇
