### ISSUE TITLE
Permission denied when trying to start project server in Windows

### ISSUE THREAD

**Issue by YizhePKU** [mbutterick/pollen#217]
Running `raco pollen start` gives:

> pollen: starting project server ...
> pollen: welcome to Pollen 2.2.2390.574 (Racket 7.6)
> pollen: project root is C:\Users\29471\OneDrive\pollen\
> pollen: project server is http://localhost:8080 (Ctrl+C to exit)
> pollen: project dashboard is http://localhost:8080/index.ptree
> pollen: ready to rock
> tcp-listen: listen failed
>   port number: 8080
>   system error: 以一种访问权限不允许的方式做了一个访问套接字的尝试。; errid=10013

Then the program quits.

The Chinese text in that message basically means "Permission denied when trying to open a socket."

I'm on Windows 10. I tried turning off firewall, but the problem persists.

**Comment by mbutterick** [comment]
I doubt this has anything to do with Pollen. I can start the project server on Windows 10 without an error. It’s possible something is already occupying port 8080. You can try a different port with  `raco pollen start . 888` (where `888` is any TCP port number).

**Comment by YizhePKU** [comment]
Thanks for the quick reply. Yes it was because of port conflicts. Problem resolved now. Probably a good idea to insert a check to warn the user though.

Again, many thanks.
