### ISSUE TITLE
Project server: consider using --local switch by default?

### ISSUE THREAD

**Issue by Macavirus** [mbutterick/pollen#220]
Not using this by default relies on user finding much later in docs that they have insecurely opened a port to the wide internet.

I think secure-by-default probably makes more sense, and explicitly opening the port when desired can be done by adding a flag, or using another tool like `ngrok`.

**Comment by mbutterick** [comment]
I’m not going to change the behavior, but I’ve added a note to the Quick Tour.

**Comment by Macavirus** [comment]
Great! Appreciate the quick fix

**Comment by mbutterick** [comment]
See also #143 and #13
