### ISSUE TITLE
Server won't render 404.html: "File not found. Sorry."

### ISSUE THREAD

**Issue by ergl** [mbutterick/pollen#222]
The pollen server won't let you access a file named `404.html` if its at the root of the pollen project, as it clashes with the [built-in 404.html page](https://github.com/mbutterick/pollen/blob/master/pollen/private/server-extras/404.html). I see you added a custom 404 message for the server in #94 so this file might be something that was never removed after that.

**Comment by sorawee** [comment]
More generally, everything in the `server-extras` directory will override existing files. `favicon.ico` is another one that it probably should not do that.

**Comment by mbutterick** [comment]
Thanks for the report!
