### ISSUE TITLE
Pollen build problem: "undeclared dependency"

### ISSUE THREAD

**Issue by celtic-coder** [mbutterick/pollen#223]
Hi Matthew,

The [Racket package indes](https://pkgd.racket-lang.org/pkgn/search?tags=author%3Amb%40mbtype.com) shows the following build problem for [Pollen](https://pkg-build.racket-lang.org/server/built/deps/pollen.txt). It closes with the summary:

    raco setup: --- summary of package problems ---
    raco setup: undeclared dependency detected
    raco setup:   for package: "pollen"
    raco setup:   on package:
    raco setup:    "net-lib"
    The time is now Sunday, April 26th, 2020 11:12:47am

Kind Regards,
Liam

**Comment by sorawee** [comment]
Suggested change: add `raco setup -D --check-pkg-deps pollen` to `.travis.yml` so that the CI will fail when this kind of problem occurs. See an example at https://github.com/greghendershott/travis-racket/blob/master/example/.travis.yml

**Comment by mbutterick** [comment]
Thanks!
