### ISSUE TITLE
Pollen server does not show any error if pollen.rkt is invalid 

### ISSUE THREAD

**Issue by arnaudchenyensu** [mbutterick/pollen#224]
Hi,

I just started with `Pollen` and I notice that the `Pollen` server does not show any error if my `pollen.rkt` file contains invalid code.

Am I doing something wrong?

I'm on Linux (Manjaro) using Pollen 2.2.2473.915 (Racket 7.6)

**Comment by otherjoel** [comment]
Can you provide the steps to reproduce what you’re seeing?

**Comment by arnaudchenyensu** [comment]
I just realized that you get an error but only if you open the file to render (in this example `document.html`), but nothing when you are viewing the `index.ptree`.

`document.poly.pm`

```
#lang pollen

This is a document.
```

`pollen.rkt`

```
#lang racket/base

(require
  pollen/decode
  quadwriter
  txexpr)

(provide (all-defined-out))

(module setup racket/base
  (provide (all-defined-out))
  (define poly-targets '(txt pdf)))

(define (root . xs)
  (case (current-poly-target)
    [(pdf) `(q ,@(add-between (decode-paragraphs xs 'q) para-break))]
    [else xs]))
```

My stupid mistake is that I couldn't understand why I couldn't see `document.txt` and `document.pdf`. I did not think about opening `document.html`.

**Comment by mbutterick** [comment]
Closing as moot.
