### ISSUE TITLE
Typo: prepreocessor -> preprocessor

### ISSUE THREAD

**Issue by wls** [mbutterick/pollen#227]
In `pollen/scribblings/tutorial-third.scrbl`, line 518, an extra 'e' made it into a word.
Change prepreocessor to preprocessor.

```
518 -   ..., because the prepreocessor automatically converts numbers to strings.
518 +   ..., because the preprocessor automatically converts numbers to strings.
```

_During the process of creating a pull request, your [contributing guidelines](https://github.com/mbutterick/pollen/blob/master/CONTRIBUTING.md) stated that it was easier for you to have an issue opened and change it yourself, rather than review PRs; hence this._

**Comment by mbutterick** [comment]
Thanks!
