### ISSUE TITLE
scribble documentation and contract for decode-paragraphs don't match 

### ISSUE THREAD

**Issue by odanoburu** [mbutterick/pollen#234]
https://github.com/mbutterick/pollen/blob/88c354cb5fcc49e806edad2a0b013ed47ac39525/pollen/decode.rkt#L200-L206 versus https://github.com/mbutterick/pollen/blob/88c354cb5fcc49e806edad2a0b013ed47ac39525/pollen/scribblings/decode.scrbl#L301-L307

where the first argument is `(listof xexpr?)` in the latter and `txexpr-elements?` in the former

**Comment by mbutterick** [comment]
Thanks!
