### ISSUE TITLE
dt is not in the default block-tags list

### ISSUE THREAD

**Issue by matteodelabre** [mbutterick/pollen#236]
Thanks for your much-appreciated work on Pollen.

The `<dt>` tag does not seem to be in Pollen’s [`block-tags` list](https://github.com/mbutterick/pollen/blob/bd154d2a2dc1612b7ce3a7e535247cbfe118d4cd/pollen/setup.rkt#L85) but appears instead in the `inline-tags` list. This is not consistent with [MDN’s classification](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements#Elements) of block-level tags, which is linked in Pollen’s docs. I noticed this because `decode` was wrapping my `<dt>`s with `<p>` tags, which produces invalid HTML.

Is this intended?

**Comment by mbutterick** [comment]
Thanks! Accidental omission, I guess.
