### ISSUE TITLE
Render uses wrong poly-target when specifying output file

### ISSUE THREAD

**Issue by otherjoel** [mbutterick/pollen#237]
I think this is a relatively recent regression. In a project containing only the following:

 * A `pollen.rkt` containing only a `setup` module that defines/provides a value for `poly-targets` of `'(html txt)` 
 * A simple `test.poly.pm` file (`#lang pollen`)

Rendering to `.txt` by specifying the desired output file produces an HTML file instead:

    > raco pollen render test.txt
    pollen: rendering test.txt
    pollen: rendering /test.poly.pm as html
    pollen: rendered /test.html (389 ms)

It still works if you specify the output format explicitly with `-t` though:

    > raco pollen render -t txt test.poly.pm
    pollen: rendering test.poly.pm
    pollen: rendering /test.poly.pm as txt
    pollen: rendered /test.txt (380 ms)

**Comment by mbutterick** [comment]
> relatively recent regression

Thanks! Seems to have been lurking since November 2019. Fixed by #238.
