### ISSUE TITLE
path->pagenode returns incorrect path if starting-path is an immediate relative filename

### ISSUE THREAD

**Issue by stschmid** [mbutterick/pollen#241]
```
> (path->pagenode "assets" 'index.html)
'../assets
```

`(dirname path)` (respectively `(split-path path)`) returns `'relative` for an immediate relative filename.
`(path->pagenode p [starting-path])` should return `p` if `(eq? starting-dir 'relative)`.

**Comment by mbutterick** [comment]
Thanks!
