### ISSUE TITLE
function for determining path to pollen.rkt

### ISSUE THREAD

**Issue by mbutterick** [mbutterick/pollen#251]
[According to](https://github.com/mbutterick/pollen-users/issues/86#issuecomment-792350555) @otherjoel:

> It would be nice to have a Pollen-provided way of determining the path to the pollen.rkt file that applies to a particular Pollen source file. I could write my own (i.e., basically copy get-path-to-override from pollen/setup) but it seems more future-proof and less redundant to ask Pollen.

**Comment by mbutterick** [comment]
This function is now exported from `pollen/setup` as `find-nearest-default-directory-require`. For now I’m not going to add it to the public documentation, but maybe later, if it works the way you hope.

**Comment by otherjoel** [comment]
So far, this is working great!
