### ISSUE TITLE
How to set html head tag

### ISSUE THREAD

**Issue by gvolk0** [mbutterick/pollen#260]
Hello, as per title, how do I set the `<head>` tag correctly?

Best I got to was using a near-empty `template.html` with just a `◊(->html ◊doc)` in it but it still wraps everything in `<root>...</root>` which isn't valid html.

What's the correct way of doing this or at least eliminating the root tag?

I'd like to be able to spell out the full html tree without relying on a shared template file.

Thank you for this great project!

**Comment by mbutterick** [comment]
These two entries in the documentation have the complete answer.

https://docs.racket-lang.org/pollen/second-tutorial.html#%28part._tutorial-2._.The_doc_export_and_the_-_html_function%29

https://docs.racket-lang.org/pollen/Template.html#%28def._%28%28lib._pollen%2Ftemplate%2Fhtml..rkt%29._-~3ehtml%29%29

**Comment by gvolk0** [comment]
Ah, I somehow missed the module section (I'm new to the whole racket ecosystem) - thanks, sorry for the noise!

**Comment by gvolk0** [comment]
yep, I realised that straight after, thought it was just syntax highlighting.

cheers.
