### ISSUE TITLE
Comparison with bookdown features

### ISSUE THREAD

**Issue by adamiturabi** [mbutterick/pollen#267]
I'm evaluating migrating my project from bookdown to Pollen (mainly because I wholeheartedly agree with Pollen's description of the limitations of markdown). I've been going through the documentation and have a couple of basic questions regarding features that I'm used to from bookdown:

1. Does Pollen have feature complete defaults (default templates?) that can allow you to produce a [gitbook style](https://github.com/GitbookIO/gitbook) or scribble/docs.racket-lang style online book, and simultaneously a featureful Latex or Xelatex output (with support for packages like geometry, polyglossia, longtable, etc.)? For the online book that would mean a layout with a contents sidebar, default fonts, navigation links, etc. This would facilitate focusing on content and relegate tinkering with layout design to later when you're done with the content. If these defaults don't exist do you think they would be useful to add to Pollen?
2. Why are file names so fundamental to Pollen, in that a source file produces an output file with the same name? Would it be more flexible to allow output file names and hierarchy to depend on a separate book layout config, e.g., chapter headings vs section headings, etc.

**Comment by otherjoel** [comment]
1. No, you need to create your own templates. The “Principle of Necessity” from the [contributing guidelines](https://github.com/mbutterick/pollen/blob/master/CONTRIBUTING.md) suggest that templates intended for reuse by many people would be best created as separate 3rd-party projects.
2. File names are fundamental to Pollen's built-in rendering facilities, but you can program your project to handle them however you wish. For example, you could create a `build.rkt` that loads up the `doc` and `metas` exported from any set of Pollen source files and combine them into a single output file based on a layout configured in a pagetree file or some other structured format. It's all Racket under the hood, so you can implement any mechanism that would be feasible in a general-purpose programming language.

**Comment by adamiturabi** [comment]
Thanks very much. And apologies: it looks like I should have posted this to https://github.com/mbutterick/pollen-users instead of here.

By the way, do you know if there are any 3rd party projects that have created these general-purpose templates for web books and Latex? It seems like it would fulfill something needed by many users.

**Comment by mbutterick** [comment]
1. Pollen is a programming system. It deliberately has a steeper learning curve than other publishing systems so that new users can evaluate it accurately. Corollary: if you want a turnkey system, you will likely be disappointed by Pollen.

2. If you want a “scribble/docs.racket-lang style online book”, you might consider using Scribble itself, which includes a LaTeX renderer.
