### ISSUE TITLE
render and clone have no effect

### ISSUE THREAD

**Issue by basus** [mbutterick/pollen#36]
I have a small example with a few ``.pm`` and ``.pmd`` files. I can see the rendered files in a browser correctly after doing ``raco pollen start``, but clone and render seem to have no effect. I don't see any errors in the terminal either.

**Comment by mbutterick** [comment]
What platform (Windows / OS X / Linux)?

**Comment by basus** [comment]
This is on 64-bit Arch Linux.

**Comment by mbutterick** [comment]
If you want to post one of the files that isn't working correctly I can try it on my system.

**Comment by mbutterick** [comment]
(Meaning, there's not enough information yet for me to hypothesize about the source of the problem)

**Comment by basus** [comment]
Here are the contents I currently have in my example:

article.html.pmd
```
#lang pollen

Hello, World!
=============

This is a simple example.
```

index.html.pmd:
```
#lang pollen

Hello, World!
=============

This is a simple example.
```

pollen.html.pm

```
#lang pollen

◊h1{Written using Pollen}

◊p{Is this going to work?}
```

**Comment by basus** [comment]
I tried deleting everything and rerunning, but no luck.

**Comment by mbutterick** [comment]
Your files work fine on my system (= project server, `raco pollen render`, and `clone`). 

What perplexes me is that you can see the files rendered properly in the project server. That indicates that the software was installed correctly, the files have no syntax errors, and your project is set up correctly, etc.

When you run `raco pollen render` from your project directory, you should see something like this:

```
~/project-dir : raco pollen render article.html.pmd 
Rendering /Users/MB/project-dir/article.html.pmd
render: article.html.pmd
cpu time: 81 real time: 82 gc time: 0
```

This indicates that Pollen processed the file successfully.

If you run `raco pollen clone`, you should see something like this:
```
~/project-dir: raco pollen clone
Cloning ...
Completed to /Users/MB/Desktop/clone
```

You can't, however, clone sources that are already on the desktop. (The cloner should check for this condition and raise an error. It wasn't. I just pushed a fix.)

What are you seeing in the terminal when you run `raco pollen render ...` or `raco pollen clone`? Nothing at all?

**Comment by basus** [comment]
When I run `raco pollen render` I get the following:

```
Rendering preproc & pagetree files in directory /home/basus/documents/basus
```

When I run `raco pollen clone`, I see:

```
Cloning ...
Completed to /home/basus/clone
```

I then do see the non-source files under `/home/basus/clone`. However, if I specify a directory to the `clone` command, I get the same message, but nothing happens.

**Comment by mbutterick** [comment]
OK, I’ve pushed some fixes that I believe will fix these problems.

`raco pollen render` was giving up when there were no pagetree files in the project directory. Now, it will render all the sources it finds.

The documentation for `raco pollen clone` was incorrect (and the underlying behavior needed some improvement too). 

`raco pollen clone` will clone the current directory onto the desktop. 
`raco pollen clone source-dir`will clone source-dir to the desktop. 
`raco pollen clone source-dir dest-dir`will clone source-dir to dest-dir. 

If you just want to clone the current directory to somewhere other than the desktop, use 
`raco pollen clone . dest-dir`.

If that still doesn't help, please reopen this issue. Thanks for the report.

**Comment by basus** [comment]
Everything seems to be working fine now. Thanks!
