### ISSUE TITLE
Frustrated with lack of Install

### ISSUE THREAD

**Issue by jcall59** [mbutterick/pollen#40]
OK, I'm sure this is the Raco equivalent of "Check to make sure the computer is plugged in", but after installing Racket v6.1.1 and DR Racket, I try to install Pollen but get NOWHERE. 
![raco 6 1 1 problem](https://cloud.githubusercontent.com/assets/11449087/6630222/c923555e-c8ec-11e4-9221-21985bd3be50.PNG)
I've tried this at work, home, laptop, hardwired: always same result. Running Windows. Racket and Dr Racket seem to run - well, at least open - fine (but what do I know). 

I'm no programmer, and my GitHub account is now 5 minutes old.

**Comment by mbutterick** [comment]
Windows users need to convert the naked `raco` command to include a full path. Assuming defaults, it’s likely to be `"C:\Program Files\Racket\raco"` (include the surrounding quotes in the command), so the whole thing would look like this:

```
"C:\Program Files\Racket\raco" pkg install pollen
```

or in your case, based on the screen shot above:

```
"C:\Program Files (x86)\Racket\raco" pkg install pollen
```

To see if it’s working, you can just do

```
"C:\Program Files (x86)\Racket\raco"
```

and you should get the default `raco` help screen, which looks like this:

```
Usage: raco <command> <option> ... <arg> ...

Frequently used commands:
  docs                 search and view documentation
  make                 compile source to bytecode
  setup                install and build libraries and documentation
  pkg                  manage packages
  planet               manage Planet package installations
  exe                  create executable
  test                 run tests associated with files/directories

[etc ...]
```
There are a couple places in the docs that I note this, but you're right that I don't note it on the Installation page. So I've fixed that. Thanks.
