### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by tthorp** [mbutterick/pollen#42]
Hi. I followed the instructions on your site to install Racket 6.1.1 and Pollen on OSX Yosemite. The result of the command 'raco pkg install pollen' was initially good, but it ended in a review of errors that are making the simple "Hello World" programs fail on my machine. Below, I am pasting the error report from the installation of Pollen.

raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/sugar
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/sugar
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen/scribblings/third-tutorial-files
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during making for <pkgs>/pollen
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco setup: error: during building docs for <pkgs>/sugar/scribblings/sugar.scrbl
raco setup:   Library/Racket/6.1.1/pkgs/sugar/include.rkt:94:30: #%require: nested `for-meta' not allowed
raco setup:     at: (for-meta 0 (rename racket/match match-lambda* match-lambda*))
raco setup:     in: (#%require (for-meta 1 (just-meta 0 (for-meta 0 (rename racket/match match-lambda* match-lambda*)))))
raco setup:     context...:
raco setup:      /Applications/Racket v6.1.1/collects/racket/private/reqprov.rkt:1122:2
raco setup:   
raco pkg install: packages installed, although setup reported errors

**Comment by mbutterick** [comment]
Thanks for the report. I made a change to one of the underlying packages today (`sugar`) and didn’t notice that error. I’ve pushed a fix. If you do `raco pkg update --update-deps pollen` you’ll get the update & all should be well.
