### ISSUE TITLE
Mailing list?

### ISSUE THREAD

**Issue by nyholku** [mbutterick/pollen#62]
Hi,

I've been flirting with Pollen for somedays now and going over the tutorials several times. In theory 'I get' most of the things but in practice I've got some way to go.

Is there a mailing list or some other forum where help could be sought? 

Seems to go a bit against the grain to submit an issue just to ask for clarification on something or other...besides with the distributed and unorganised nature of github it may become unclear in who's repo the discussions should go on.

**Comment by mbutterick** [comment]
OK, you got it — pollenpub@googlegroups.com
