### ISSUE TITLE
directory-require.rkt is not reloaded when changed

### ISSUE THREAD

**Issue by wolverian** [mbutterick/pollen#64]
While `raco pollen start` is running, changing `directory-require.rkt` doesn't seem to have any effect. Would it be possible to change this so that when changes are made to that file the server notices that and reloads the appropriate stuff?

**Comment by mbutterick** [comment]
It is, in principle, supposed to reload, but that’s become less dependable as I’ve added caching mechanisms for speed. I’m in the midst of rethinking the cache-invalidation mechanisms. It may also be worthwhile to add a “development” mode that disables all the caches.

**Comment by mbutterick** [comment]
Relatedly: https://github.com/plt/racket/issues/971

**Comment by mbutterick** [comment]
Still working on the big-picture fix. As a workaround, you can now turn off the compile cache, so everything in the page gets recompiled every time (slower but has the side effect of reloading "directory-require.rkt" as well).

To turn off the compile cache, add the following `config` submodule to your "directory-require.rkt" file:

```racket
(module config racket/base
  (provide (all-defined-out))
  (define compile-cache-active #f))
```
