### ISSUE TITLE
`raco pollen hello.txt.pp` crash on Win64

### ISSUE THREAD

**Issue by maphew** [mbutterick/pollen#72]
Brand new to Racket and Pollen; am following [Quick Tour][1] tutorial and at section 2.3 running `raco pollen hello.txt.pp` crashes with a popup dialog: _"Racket application has stopped working. A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available."_

Racket 6.2 (installed via racket-6.2-x86_64-win32.exe)
Windows 7 Home Premium 64-bit SP1

![2015-07-17 02_19_18-racket application](https://cloud.githubusercontent.com/assets/486200/8744236/79fe5ca2-2c2a-11e5-80bb-62576827714e.png)

[1]: http://pkg-build.racket-lang.org/doc/pollen/quick-tour.html

**Comment by maphew** [comment]
...ahhh, figured it out. My source file is in a [SUBST][1] drive (`B:\: => C:\Users\me\Dropbox`). 

Closing because this is probably an upstream problem with Racket/Windows and not Pollen.

[1]:http://ss64.com/nt/subst.html

**Comment by maphew** [comment]
For the record, SUBST might be a red herring, with the closer to root cause being use of Windows "[mount NTFS volume in empty folder][1]" feature

```
c:\Users\Matt\Dropbox\racket>raco pollen render hello.txt.pp
normalize-path: element within the input path is not a directory or does not exist
  element: D:\Users\Matt\Volume{05f5a0a2-b914-11e2-bba5-848f69c7e90d}
  context...:
   c:\Program Files\Racket\collects\racket\path.rkt:66:14: normalize
   C:\Users\Matt\AppData\Roaming\Racket\6.2\pkgs\pollen\command.rkt:15:0: dispatch
   (submod C:\Users\Matt\AppData\Roaming\Racket\6.2\pkgs\pollen\command.rkt raco): [running body]
   c:\Program Files\Racket\collects\raco\raco.rkt: [running body]
   c:\Program Files\Racket\collects\raco\main.rkt: [running body]
```

[1]: https://technet.microsoft.com/en-us/library/cc753321.aspx

**Comment by mbutterick** [comment]
I’ll take a look. Might be a Pollen problem but it looks like the Racket `normalize-path` function isn’t coping with the remapped drive as it ought to.

**Comment by mbutterick** [comment]
Sorry, but I have no idea, and my Windows skills are not deep enough to reproduce the problem.

**Comment by maphew** [comment]
For anyone who might investigate further the recipe to reproduce is:

1. Find a drive with no open files and nothing important on it (a USB stick will do).
2. Remove it's drive letter:
 -  Open _[Disk Management][1]_ (Start >>Run >> `diskmgmt.msc`)
 - Select volume >> R-click >> _Change Drive Letter and Paths_ >> remove letter >> OK
 - Select same volume >> R-click >> Change Drive Letter and Paths >> _[Add]_ >> Mount in following empty folder >> select folder >> OK
3. Copy pollen project to that path, e.g. `D:\mount\usb_x`, and then run `raco pollen hello.txt.pp`

[1]: http://pcsupport.about.com/od/tipstricks/f/open-disk-management.htm
