### ISSUE TITLE
Documentation down

### ISSUE THREAD

**Issue by lerichard95** [mbutterick/pollen#76]
I think the latest update to Pollen broke something... I'm new to Racket and Pollen so I can't offer any tips about what might be going on, but I have a feeling it's related to the Racket package system. 

The documentation links from http://pollenpub.com/ are currently not working. I've pasted the error messages below. Just when I was trying to show someone how cool Pollen was, too!

From http://pkg-build.racket-lang.org/doc/pollen/
<pre>
403 Forbidden

Code: AccessDenied
Message: Access Denied
RequestId: 228969362BDDB98B
HostId: L1wtTiQcfDbVmB9c26ZXLe/43xyKp4aj3xUsBXTahHpJfen+yAhPfBI5engICfiCYhDBn3JvzXY=
</pre>

From http://racket-lang.org/doc/pollen/
<pre>
> ((uncaught-exception-handler)
   (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*))))
uncaught exception: 404
</pre>

The build status is listed as "failed" on the Racket package site http://pkgs.racket-lang.org

<pre>The time is now Friday, July 31st, 2015 6:21:50am
/usr/bin/ssh -R 18333:localhost:18333 racket@192.168.56.108 '/usr/bin/env' 'DISPLAY=:1' 'PLT_PKG_BUILD_SERVICE=1' 'PLTUSERHOME=/home/racket/build-pkgs/user' '/bin/sh' '-c' 'cd "/home/racket/build-pkgs"/racket && bin/raco pkg install -u --auto pollen'
Resolving "pollen" via http://localhost:18333/built/catalog/
Resolving "pollen" via http://localhost:18333/archive/catalog/
Downloading https://github.com/mbutterick/pollen/tarball/ce9f652c5597a206776606783692e9be4d8e2045
tcp-connect: connection failed
  detail: host not found
  address: github.com
  port number: 443
  step: 1
  system error: Name or service not known; errno=-2
  context...:
   /home/racket/build-pkgs/racket/collects/openssl/mzssl.rkt:1626:0: ssl-connect118
   /home/racket/build-pkgs/racket/collects/net/http-client.rkt:220:0
   /home/racket/build-pkgs/racket/collects/net/url.rkt:130:0: http://getpost-impure-port
   /home/racket/build-pkgs/racket/collects/net/url.rkt:264:2: redirection-loop
   /home/racket/build-pkgs/racket/collects/pkg/private/download.rkt:21:0: call/input-url+2007
   /home/racket/build-pkgs/racket/collects/file/cache.rkt:63:2: fetch-and-continue
   /home/racket/build-pkgs/racket/collects/pkg/private/stage.rkt:327:14
   /home/racket/build-pkgs/racket/collects/pkg/private/stage.rkt:74:0: stage-package/info42
   /home/racket/build-pkgs/racket/collects/pkg/private/stage.rkt:74:0: stage-package/info42
   /home/racket/build-pkgs/racket/collects/pkg/private/install.rkt:618:4: for-loop
   /home/racket/build-pkgs/racket/collects/pkg/private/install.rkt:125:0: install-packages68
   /home/racket/build-pkgs/racket/collects/racket/file.rkt:368:8
   /home/racket/build-pkgs/racket/collects/racket/file.rkt:357:0: call-with-file-lock40
   /home/racket/build-pkgs/racket/collects/pkg/main.rkt:223:16
   (submod /home/racket/build-pkgs/racket/collects/pkg/main.rkt main): [running body]
The time is now Friday, July 31st, 2015 6:21:51am
</pre>

**Comment by mbutterick** [comment]
Based on the error, it looks like there was a temporary network connection problem. I’m going to let this sit till tomorrow and see what happens (it will probably rebuild on its own)

**Comment by mbutterick** [comment]
This was an issue with Racket’s build server, now fixed in https://github.com/plt/racket/commit/bf76ced8ba.
