### ISSUE TITLE
Is "t" type face sizing really shorter than neighbour letters?

### ISSUE THREAD

**Issue by maphew** [mbutterick/pollen#79]
This probably isn't a pollen issue per se, but I noticed this weird small rendering of "t" in strong text when going through the 3rd tutorial today, on a computer I haven't used in awhile and figured you'd want to know about it.

![pollen_t_is_small](https://cloud.githubusercontent.com/assets/486200/9321430/36c2513c-451b-11e5-895d-be9c6bcf6616.png)

Screenshot taken of Firefox rending text at 100%, then blown up in Paint.net using cubic resampling. Using native FF scaling keeps the text sharp, but the out of step small 't' is not as obvious then:

![pollen_t_is_small_ff](https://cloud.githubusercontent.com/assets/486200/9321488/1b38ba2c-451c-11e5-83d1-4dbe826c9d30.png)

Firefox 39 on Win7-x64.

**Comment by mbutterick** [comment]
Looks like a TrueType hinting problem in the Charter Bold font used in the Racket documentation. I’ll see if there’s anything to be done about it, but it’s not strictly Pollen related.
