### ISSUE TITLE
Environmental variables are cached by Pollen

### ISSUE THREAD

**Issue by fasiha** [mbutterick/pollen#86]
Borrowing a page from the web development crowd, I'm using an environmental variable called `TESTING` to control behavior of my Pollen build. When I'm testing on my local machine, I want the rendered output to use a local copy of MathJax, e.g., but for production, I want it to point to the CDN. If my Pollen markup file contains `◊(define-meta development (getenv "TESTING"))`, then my template can `select-from-metas` and detect when I run `$ TESTING=1 raco pollen render file.html` vs just `raco pollen …`.

However, for this to work in practice, I have to delete the pollen-cache directory. It would appear that the result of `getenv` is cached and reused.

I'm tempted to disable caching (I saw how to in one of these issues using a config module) because Pollen's CPU time is lower after I delete cache than if I don't (180 vs 260), but I thought I should send a note and see if there was a better way forward.

**Comment by mbutterick** [comment]
Yes, disabling the compile cache in your `pollen.rkt` will work:

```racket
(module config racket/base
  (provide (all-defined-out))
  (define compile-cache-active #f))
```

I’ve also just pushed an update that makes the cache look for a `POLLEN` environment variable (= more general designator than `TESTING`). So this: 

```
$ POLLEN=1 raco pollen render file.html
```

will not compile the same way as this:

```
$ raco pollen render file.html
```

**Comment by mbutterick** [comment]
Meaning, if you use the `POLLEN` environment variable, you needn’t disable the cache.

**Comment by mbutterick** [comment]
As for all the other environment variables … this runs into the general problem of cache invalidation. You can always create a new dependency from afar. The only way for the Pollen cache to be certain that something hasn’t changed is to compile afresh every time (which of course would be the equivalent of not caching at all). 

So for the cache to be useful, there has to be a limit on the horizon of dependency checking. For those who need true unfettered dynamism, disabling the cache is the solution.

BTW there is also a render cache, so the whole cache-disabling config would be this:

```racket
(module config racket/base
  (provide (all-defined-out))
  (define compile-cache-active #f)
  (define render-cache-active #f))
```

**Comment by fasiha** [comment]
Most awesome, thank you good sir 👍!

**Comment by mbutterick** [comment]
I use this a lot now. Good idea!
