### ISSUE TITLE
Results of example code for select-from-metas show only errors

### ISSUE THREAD

**Issue by otherjoel** [mbutterick/pollen#88]
In the documentation, the results for example code under the [`select-from-metas`](http://pkg-build.racket-lang.org/doc/pollen/Template.html#%28def._%28%28lib._pollen%2Ftemplate..rkt%29._select-from-metas%29%29) function show only errors.

**Comment by mbutterick** [comment]
Thanks.

**Comment by mbutterick** [comment]
Revise this example to use inline `pollen` module
